baseURL: /
languageCode: en-us
theme: aafu
params:
  aboutme:
    description: I'm a PhD candidate in the Department of Population and Public Health Sciences at Keck School of Medicine, University of Southern California. My dissertation research is funded by an NIH/NIDA F31 predoctoral fellowship. I'm a trainee of the Center for Applied Network Analysis (CANA) and the Center for Young Adult Cancer Survivorship (CYACSR).
    icon: fas fa-user
    title: About Me
  author: Sarah E. Piombo
  copyright: short copyright message
  description: Sarah E. Piombo
  education:
    icon: fas fa-graduation-cap
    list:
      - college: Keck School of Medicine, University of Southern California
        dates: 2019 - Present
        degree: Ph.D. in Health Behavior Research
        #thesis_title: 'Department of Preventive Medicine'
        #thesis_url: '#'
      - college: University of Southern California
        dates: 2016 - 2018
        degree: MPH, emphasis in Biostatistics & Epidemiology
        #thesis_title: 'Effect of humans on other humans: a study of human behavior.'
        thesis_url: '#'
      - college: Santa Clara University
        dates: 2012 - 2016
        degree: B.S. in Public Health Science and Psychology
    title: Education
  experience:
    icon: fas fa-briefcase
    list:
      - company: Social Network Analysis
        #dates: 2019 - *Present*
        details: I believe that many public health issues can benefit from taking a network level approach to gain insight on the social dynamics that impact health behaviors and outcomes.I use social network analysis to understand the individual and structural factors that give rise to public health issues. I use network analytic techniques to determine pathways for interventions with the objective of optimizing intervention outcomes by leveraging the preexisting network structure. 
        #position: Job Title
     # - company: I'm well versed in social network methodology and have experience analyzing both sociometric and egocentric network data. I regularly use exponential random graph models (ERGMs), stochastic actor-oriented models (SAOM/RSIENA), and multilevel modeling techniques.
        #dates: 
       # position: youngadultsurvivors.org
      #  details: 
       # url: '#'
      - company: I've analyzed network influence on a variety of health behaviors and outcomes including cigarette use, e-cigarettes/vaping, marijuana use, BMI, physical activity, social support among cancer patients, physician referral patterns, and women's health. In addition to my academic work, I have applied these methods to other settings including team dynamics in corporate organizations and inter-organization collaboration networks.  
    title: Research
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\n        "
    use: no
  #hobby:
   # icon: fas fa-gamepad
    #list:
     # - hobby: Cooking
      #- hobby: Hiking
      #- hobby: Baking
    #title: Hobbies
  profile:
    location: Los Angeles, CA
    name: Sarah E. Piombo, MPH
    photo: sarah.JPG
    tagline: PhD Candidate in Health Behavior Research
  project:
    icon: fas fa-project-diagram
    list:
      - description: Description of the project
        title: Project 1
        url: '#'
      - description: Description of the project
        title: Project 2
        url: '#'
      - description: Description of the project
        title: Project 3
        url: '#'
      - description: Description of the project
        title: Project 4
        url: '#'
    title: Projects
  publication:
    format:
      - authors
      - date
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: Valente TW, Piombo SE, Edwards KM, Waterman EA, & Banyard VL
        date: '2023'
        journal: Substance Use and Misuse
        title: 'Influences on Adolescent E-cigarette Use'
        type: Journal Articles
        url: ''
      - authors: Piombo SE,* Stal J,* Kysh L, Kagramanov D, Freyer DR, Turner BJ, Hempel S, & Miller KA
        date: '2022'
        journal: J. of Cancer Survivorship
        title: 'The integration of primary care and childhood cancer survivorship care: A scoping review.' 
        type: Journal Articles
        url: 'https://pubmed.ncbi.nlm.nih.gov/36534343/'
      - authors: Piombo SE, Miller KA, Freyer DR,  Milam J, Ritt-Olson A, In GK, Valente TW  
        date: '2022'
        journal: Communications Medicine
        title: 'Social Networks of Oncology Clinicians as a Means for Increasing Survivorship Clinic Referral'
        type: Journal Articles
        url: 'https://rdcu.be/c0Olt'
      - authors: Piombo SE,* Stal J,* Kagramanov D, Kysh L, Freyer D, Turner B, Miller KA
        date: '2022'
        journal: BMJ Open
        title: 'Integrating primary care and childhood cancer survivorship care: A scoping review protocol'
        type: Journal Articles
        url: 'https://bmjopen.bmj.com/content/12/5/e059050'        
      - authors: Piombo SE, Huh J, Valente TW
        date: '2022'
        journal: Childhood Obesity
        title: 'Adolescent Body Mass Index and Exposure to Peers with Overweight and Obesity: A Structural Equation Model Approach to Longitudinal Network Data'
        type: Journal Articles
        url: 'https://pubmed.ncbi.nlm.nih.gov/35108122/'
      - authors: Miller KA, Huh J, Piombo SE, Richardson JL, Harris SC, Peng DH, Cockburn MG
        date: '2021'
        journal: Preventive Medicine
        title: 'Sun protection changes among diverse elementary schoolchildren participating in a sun safety intervention: a latent transition analysis of a randomized controlled trial.'
        type: Journal Articles
        url: 'https://pubmed.ncbi.nlm.nih.gov/33971211/'
      - authors: Piombo SE, Miller KA, Alderete K., Egan A, Golingay S, Valente TW
        date: '2020'
        journal: Journal of Cancer Education.
        title: Evaluation of a Nurse-Delivered Pre-Chemotherapy Educational Intervention to Increase Knowledge and Reduce Anxiety Among Ethnically Diverse Patients.
        type: Journal Articles
        url: 'https://pubmed.ncbi.nlm.nih.gov/32002822/'
      - authors: Miller KA, Piombo SE, Cho J, Higgins S, Wysong A, Sussman S, Cockburn MG, Leventhal AM
        date: '2018'
        journal: Journal of Investigative Dermatology.
        title: Prevalence of tanning addiction and associations with behavioral health conditions among ethnically and racially diverse adolescents.
        type: Journal Articles
        url: 'https://pubmed.ncbi.nlm.nih.gov/29481903/'
      
     # - authors: F Last, F Second, P secondary
      #  date: '2018'
       # journal: Journal of Field 52 (16), 9033-9044
        #title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
         # tempor incididunt ut labore et dolore magna aliqua.
        #type: Proceedings
        #url: '#'
    title: Publications
    types:
      - Journal Articles
      #- Proceedings
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience 
    - item: education
    - item: publication
    #- item: project
    - item: skill
    #- item: hobby
  skill:
    icon: fas fa-cogs
    description: I'm well versed in social network methodology and have experience analyzing both sociometric and egocentric network data. I regularly use exponential random graph models (ERGMs), stochastic actor-oriented models (SAOM/RSIENA), and multilevel modeling techniques. 
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: 'https://www.linkedin.com/in/sarahpiombo'
 #     - icon: fab fa-stack-overflow
  #      title: StackOverflow
   #     url: '#'
    #  - icon: fab fa-github
     #   title: GitHub
      #  url: '#'
      - icon: fab fa-twitter
        title: Twitter
        url: 'https://twitter.com/sarah_piombo'
      - icon: fab fa-orcid
        title: Orcid
        url: 'https://orcid.org/0000-0001-5118-7897'
   #   - icon: ai ai-google-scholar
    #    title: Google Scholar
     #   url: '#'
      - icon: fab fa-researchgate
        title: ResearchGate
        url: 'https://www.researchgate.net/profile/Sarah-Piombo'
    title: Links
  theme:
    mainTheme: pinkish
    showAttribute: yes
    singlePage: no
  title: Sarah E. Piombo

markup:
  goldmark:
    renderer:
      unsafe: true
