baseURL: /
languageCode: en-us
theme: aafu
params:
  aboutme:
    description: I'm a PhD student in the Department of Population and Public Health Sciences at Keck School of Medicine, University of Southern California. I'm a trainee of the Center for Applied Network Analysis (CANA) and the Center for Young Adult Cancer Survivorship (CYACSR).
    icon: fas fa-user
    title: About Me
  author: Darshan Baral
  copyright: short copyright message
  description: Sarah E. Piombo
  education:
    icon: fas fa-graduation-cap
    list:
      - college: University of Southern California
        dates: 2019 - Present
        degree: Ph.D. in Health Behavior Research
        #thesis_title: 'Department of Preventive Medicine'
        #thesis_url: '#'
      - college: University of Southern California
        dates: 2016 - 2018
        degree: MPH in Biostatistics & Epidemiology
        #thesis_title: 'Effect of humans on other humans: a study of human behavior.'
        thesis_url: '#'
      - college: Santa Clara University
        dates: 2012 - 2016
        degree: B.S. in Public Health Science and Psychology
    title: Education
  experience:
    icon: fas fa-briefcase
    list:
      - company: Social Network Analysis
        #dates: 2019 - *Present*
        details: Using social network analysis to explore personal and network factors that impact health behaviors, with a research focus on electronic nicotine delivery systems among youth.  
        #position: Job Title
      - company: Young Adult Cancer Survivorship Research
        #dates: 
       # position: youngadultsurvivors.org
        details: Using program evaluation and implementation science to inform interventions that improve quality of life and health outcomes among AYA cancer patients and survivors.
       # url: '#'
    title: Research
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\n        "
    use: yes
  #hobby:
   # icon: fas fa-gamepad
    #list:
     # - hobby: Cooking
      #- hobby: Hiking
      #- hobby: Baking
    #title: Hobbies
  profile:
    location: Los Angeles, CA
    name: Sarah E. Piombo, MPH
    photo: sarah.JPG
    tagline: PhD student in Health Behavior Research
  project:
    icon: fas fa-project-diagram
    list:
      - description: Description of the project
        title: Project 1
        url: '#'
      - description: Description of the project
        title: Project 2
        url: '#'
      - description: Description of the project
        title: Project 3
        url: '#'
      - description: Description of the project
        title: Project 4
        url: '#'
    title: Projects
  publication:
    format:
      - date
      - authors
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: Piombo SE, Miller KA, Alderete K., Egan A, Golingay S, Valente TW
        date: '2020'
        journal: Journal of Cancer Education.
        title: Evaluation of a Nurse-Delivered Pre-Chemotherapy Educational Intervention to Increase Knowledge and Reduce Anxiety Among Ethnically Diverse Patients.
        type: Journal Articles
        url: 'https://doi.org/10.1007/s13187-020-01695-4'
      - authors: Miller KA, Piombo SE, Cho J, Higgins S, Wysong A, Sussman S, Cockburn MG, Leventhal AM
        date: '2018'
        journal: Journal of Investigative Dermatology.
        title: Prevalence of tanning addiction and associations with behavioral health conditions among ethnically and racially diverse adolescents.
        type: Journal Articles
        url: '#'
      - authors: Miller KA, Huh J, Piombo SE, Richardson JL, Harris SC, Peng DH, Cockburn MG
        date: '2021'
        journal: Preventive Medicine
        title: 'Sun protection changes among diverse elementary schoolchildren participating in a sun safety intervention: a latent transition analysis of a randomized controlled trial.'
        type: Journal Articles
        url: '#'
     # - authors: F Last, F Second, P secondary
      #  date: '2018'
       # journal: Journal of Field 52 (16), 9033-9044
        #title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
         # tempor incididunt ut labore et dolore magna aliqua.
        #type: Proceedings
        #url: '#'
    title: Publications
    types:
      - Journal Articles
      #- Proceedings
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience 
    - item: education
    - item: publication
    #- item: project
    - item: skill
    #- item: hobby
  skill:
    icon: fas fa-cogs
    description: R, Stata, Mplus, SAS
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: 'https://www.linkedin.com/in/sarahpiombo'
 #     - icon: fab fa-stack-overflow
  #      title: StackOverflow
   #     url: '#'
    #  - icon: fab fa-github
     #   title: GitHub
      #  url: '#'
    #  - icon: fab fa-twitter
     #   title: Twitter
      #  url: '#'
      - icon: fab fa-orcid
        title: Orcid
        url: 'https://orcid.org/0000-0001-5118-7897'
   #   - icon: ai ai-google-scholar
    #    title: Google Scholar
     #   url: '#'
      - icon: fab fa-researchgate
        title: ResearchGate
        url: 'https://www.researchgate.net/profile/Sarah-Piombo'
    title: Links
  theme:
    mainTheme: pinkish
    showAttribute: yes
    singlePage: no
  title: Aafu theme

markup:
  goldmark:
    renderer:
      unsafe: true
